default_language_version:
    python: python3.11
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: input.txt
    -   id: end-of-file-fixer
        exclude: input.txt
    -   id: check-added-large-files
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: "v0.1.6"
  hooks:
    - id: ruff
    - id: ruff-format
